routes/web.php
<?php

use App\Http\Controllers\AdminController;
use App\Http\Controllers\ChartController;
use App\Http\Controllers\CustomerController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\NotificationController;
use App\Http\Controllers\QrCodeController;
use App\Http\Controllers\SuperadminController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
// 	return view('auth.login');
// });

Route::get('/', function () {
	return redirect()->route('login');
});

Route::get('/home', [HomeController::class, 'index'])->name('home');
Route::get('/qrcode', [QrCodeController::class, 'index']);

// Route::middleware('guest')->group(function);
Route::name('superadmin.')->middleware('superadmin')->group(function () {
	Route::get('/superadmin', [SuperadminController::class, 'index'])->name('home');
	Route::get('/list-admin', [SuperadminController::class, 'listAdmin'])->name('list-admin');
	Route::get('/create-admin', [SuperadminController::class, 'createAdmin'])->name('create-admin');
	Route::post('/store-admin', [SuperadminController::class, 'storeAdmin'])->name('store-admin');
	Route::get('/edit-admin/{admin}', [SuperadminController::class, 'editAdmin'])->name('edit-admin');
	Route::put('/update-admin/{admin}', [SuperadminController::class, 'updateAdmin'])->name('update-admin');
	Route::delete('/delete-admin/{admin}', [SuperadminController::class, 'destroyAdmin'])->name('delete-admin');
	Route::delete('/delete-customer/{customer}', [SuperadminController::class, 'deleteCustomer'])->name('delete-customer');
});

Route::name('admin.')->middleware('admin')->group(function () {
	Route::get('/admin', [AdminController::class, 'index'])->name('home');
	Route::get('/charts', [AdminController::class, 'indexChart'])->name('charts');
	Route::get('/list-product', [AdminController::class, 'listProduct'])->name('list-product');
	Route::get('/create-product', [AdminController::class, 'createProduct'])->name('create-product');
	Route::post('/store-product', [AdminController::class, 'storeProduct'])->name('store-product');
	Route::get('/edit-product/{product}', [AdminController::class, 'editProduct'])->name('edit-product');
	Route::put('/update-product/{product}', [AdminController::class, 'updateProduct'])->name('update-product');
	Route::delete('/delete-product/{product}', [AdminController::class, 'deleteProduct'])->name('delete-product');
	Route::get('/list-customer', [AdminController::class, 'listCustomer'])->name('list-customer');
	Route::delete('/delete-customer/{customer}', [AdminController::class, 'deleteCustomer'])->name('delete-customer');
	Route::get('/create-notifikasi', [AdminController::class, 'createNotifikasi'])->name('create-notifikasi');
	Route::post('/store-notifikasi', [AdminController::class, 'storeNotifikasi'])->name('store-notifikasi');
	Route::get('/create-qrcode', [AdminController::class, 'createQrCode'])->name('create-qrcode');
	Route::post('/store-qrcode', [AdminController::class, 'storeQrCode'])->name('store-qrcode');
	Route::get('/list-transaksi', [AdminController::class, 'listTransaksi'])->name('list-transaksi');
	Route::get('/getnotifpopadmin', [AdminController::class, 'getNotifPop'])->name('getnotifpopadmin');
	Route::get('/getnotifadmin', [AdminController::class, 'getNotif'])->name('getnotifadmin');
	Route::get('/getnotifclickadmin', [AdminController::class, 'getNotifClick'])->name('getnotifclickadmin');
	Route::post('/approve/{id_admin}/{id_order}', [AdminController::class, 'approve'])->name('approve');

	// Route::get('/list-customer', [CustomerController::class, 'index'])->name('list-customer');
	// Route::delete('/delete-customer/{customer}', [CustomerController::class, 'destroy'])->name('delete-customer');
});

Route::name('customer.')->middleware('customer')->group(function () {
	Route::get('/customer', [CustomerController::class, 'index'])->name('home');
	Route::get('/cart', [CustomerController::class, 'indexCart'])->name('cart');
	Route::get('/checkout', [CustomerController::class, 'indexCheckout'])->name('checkout');
	Route::get('/notifikasi', [CustomerController::class, 'indexNotifikasi'])->name('notifikasi');
	Route::post('/buynow/{id}', [CustomerController::class, 'buyNow'])->name('buynow');
	Route::get('/getnotifpop', [CustomerController::class, 'getNotifPop'])->name('getnotifpop');
	Route::get('/getnotif', [CustomerController::class, 'getNotif'])->name('getnotif');
	Route::get('/getnotifclick', [CustomerController::class, 'getNotifClick'])->name('getnotifclick');
	// Route::get('/user/profile', function () {
	//     // Uses first & second middleware...
	// });
});

Auth::routes();

resources/views/layouts/app-admin.blade.php
<!DOCTYPE html>
<html class="loading" lang="en" data-textdirection="ltr">

<!-- BEGIN: Head-->
@include('layouts.head-admin')
<!-- END: Head-->

<!-- BEGIN: Body-->

<body class="vertical-layout vertical-menu-modern navbar-floating footer-static" data-open="click"
    data-menu="vertical-menu-modern" data-col="">

    <!-- BEGIN: Header-->
    @include('layouts.header-admin')
    <!-- END: Header-->

    <!-- BEGIN: Main Menu-->
    @include('layouts.sidebar-admin')
    <!-- END: Main Menu-->

    <!-- BEGIN: Content-->
    @yield('content')
    <!-- END: Content-->

    <div class="sidenav-overlay"></div>
    <div class="drag-target"></div>

    <!-- BEGIN: Footer-->
    @include('layouts.footer-admin')
    <!-- END: Footer-->

    <!-- BEGIN: Script-->
    @include('layouts.script-admin')
    <!-- END: Script-->

    @if (Auth::user()->role->nama === 'admin')
        <!-- BEGIN: Notification JS-->
        <script>
            navigator.serviceWorker.register('sw.js');

            window.onload = function() {
                function tampilnotifikasi(data) {
                    if (Notification.premission === "granted") {
                        navigator.serviceWorker.ready.then((registration) => {
                            var notif = registration.showNotification(data['judul'], {
                                body: data['isi_pesan'],
                                icon: "/logo.png",
                            });
                            notif.onclick = function() {
                                window.open('https://www.youtube.com/', '_blank');
                            };
                        });
                    } else if (Notification.permission !== "denied") {
                        Notification.requestPermission(function(result) {
                            if (result === 'granted') {
                                navigator.serviceWorker.ready.then((registration) => {
                                    var notif = registration.showNotification(data['judul'], {
                                        body: data['isi_pesan'],
                                        icon: "/logo.png",
                                    });
                                    notif.onclick = function() {
                                        window.open('https://www.youtube.com/', '_blank');
                                    };
                                });
                            }
                        });
                    }
                }

                function countNotif() {
                    var httpxml = new XMLHttpRequest();

                    function stateck() {
                        if (httpxml.readyState == 4) {
                            var response = httpxml.responseText ? JSON.parse(httpxml.responseText) : false;
                            if (response) {
                                let bell = document.getElementById("notif");
                                if (document.getElementById("jmlh-notif")) {
                                    document.getElementById("jmlh-notif").remove();
                                }
                                bell.insertAdjacentHTML("afterend",
                                    '<span class="badge badge-pill badge-danger badge-up" id="jmlh-notif">' + response +
                                    '</span>');
                            } else {
                                // document.getElementById("jmlh-notif").innerHTML.remove();
                                return false;
                            }
                        }
                    }
                    httpxml.onreadystatechange = stateck;
                    httpxml.open("GET", "/getnotifadmin", true);
                    httpxml.send();
                }

                function AjaxFunction() {
                    var httpxml = new XMLHttpRequest();

                    function stateck() {
                        if (httpxml.readyState == 4) {
                            var response = httpxml.responseText ? JSON.parse(httpxml.responseText) : false;
                            if (response) {
                                tampilnotifikasi(response);
                            } else {
                                return false;
                            }
                        }
                    }
                    httpxml.onreadystatechange = stateck;
                    httpxml.open("GET", "/getnotifpopadmin", true);
                    httpxml.send();
                }

                countNotif();

                document.getElementById('notif').addEventListener('click', function(e) {
                    if (document.getElementById("jmlh-notif") != null) {
                        let jmlh_notif = document.getElementById("jmlh-notif").innerHTML;
                        if (jmlh_notif - 5 > 0) {
                            document.getElementById("jmlh-notif").innerHTML -= 5;
                        } else {
                            document.getElementById("jmlh-notif").remove();
                        }
                    }
                    var httpxml = new XMLHttpRequest();

                    function stateck() {
                        document.getElementById("notifications").innerHTML = "";
                        if (httpxml.readyState == 4) {
                            var response = httpxml.responseText ? JSON.parse(httpxml.responseText) : false;
                            if (response) {
                                response.forEach(function(item, index) {
                                    document.getElementById("notifications").innerHTML +=
                                        '<a class="d-flex" href="' + (item['link'] ? item['link'] :
                                            'javascript:void(0)') +
                                        '"> <div class="media d-flex align-items-start"> <div class="media-left"> <div class="avatar bg-light-warning"> <div class="avatar-content"> <svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-alert-triangle avatar-icon"><path d="M10.29 3.86L1.82 18a2 2 0 0 0 1.71 3h16.94a2 2 0 0 0 1.71-3L13.71 3.86a2 2 0 0 0-3.42 0z"></path><line x1="12" y1="9" x2="12" y2="13"></line><line x1="12" y1="17" x2="12.01" y2="17"></line></svg> </div> </div> </div> <div class="media-body"> <p class="media-heading"> <span class="font-weight-bolder">' +
                                        item['judul'] + '</span> </p> <small class="notification-text">' +
                                        item[
                                            'isi_pesan'] + '</small> </div> </div> </a>';
                                });
                            } else {
                                document.getElementById("notifications").innerHTML =
                                    '<p class="dropdown-item text-center">Tidak ada notifikasi<br></p>'
                            }
                        }
                    }
                    httpxml.onreadystatechange = stateck;
                    httpxml.open("GET", "/getnotifclickadmin", true);
                    httpxml.send();
                });

                setInterval(function() {
                    countNotif();
                    AjaxFunction();
                }, 10000);
            }
        </script>
        <!-- END: Notification JS-->
    @endif

    <!-- BEGIN: Page JS-->
    @yield('script')
    <!-- END: Page JS-->
</body>
<!-- END: Body-->

</html>

resources/views/layouts/footer-admin.blade.php
<footer class="footer footer-static footer-light pb-1 sticky-bottom">
    <p class="clearfix mb-0"><span class="float-md-left d-block d-md-inline-block mt-25">COPYRIGHT &copy; 2022<a
                class="ml-25" href="#" target="_blank">Denassyah Nurrohman</a><span
                class="d-none d-sm-inline-block">, All rights
                Reserved</span></span><span class="float-md-right d-none d-md-block">Hand-crafted & Made with<i
                data-feather="heart"></i></span></p>
</footer>
<button class="btn btn-primary btn-icon scroll-top" type="button"><i data-feather="arrow-up"></i></button>

resources/views/layouts/head-admin.blade.php
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1.0,user-scalable=0,minimal-ui">
    <meta name="description"
        content="Vuexy admin is super flexible, powerful, clean &amp; modern responsive bootstrap 4 admin template with unlimited possibilities.">
    <meta name="keywords"
        content="admin template, Vuexy admin template, dashboard template, flat admin template, responsive admin template, web app">
    <meta name="author" content="PIXINVENT">
    <title>Dashboard ecommerce - Vuexy - Superadmin Pages</title>
    {{-- <link rel="apple-touch-icon" href="../../../app-assets/images/ico/apple-icon-120.png"> --}}
    <link rel="shortcut icon" type="image/x-icon" href="{{ asset('img/vuexy/favicon.ico') }}">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,300;0,400;0,500;0,600;1,400;1,500;1,600"
        rel="stylesheet">

    <!-- BEGIN: Vendor CSS-->
    <link rel="stylesheet" type="text/css" href="{{ asset('css/vuexy/vendors.min.css') }}">
    {{-- <link rel="stylesheet" type="text/css" href="{{ asset('css/vuexy/charts/apexcharts.css') }}"> --}}
    <link rel="stylesheet" type="text/css" href="{{ asset('css/vuexy/extensions/toastr.min.css') }}">
    {{-- <script src="https://unpkg.com/feather-icons"></script> --}}
    <!-- END: Vendor CSS-->

    <!-- BEGIN: Theme CSS-->
    <link rel="stylesheet" type="text/css" href="{{ asset('css/vuexy/bootstrap.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('css/vuexy/bootstrap-extended.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('css/vuexy/colors.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('css/vuexy/components.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('css/vuexy/themes/dark-layout.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('css/vuexy/themes/bordered-layout.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('css/vuexy/themes/semi-dark-layout.css') }}">
    <!-- END: Theme CSS-->

    <!-- BEGIN: Page CSS-->
    <link rel="stylesheet" type="text/css" href="{{ asset('css/vuexy/core/menu/menu-types/vertical-menu.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('css/vuexy/pages/dashboard-ecommerce.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('css/vuexy/plugins/charts/chart-apex.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('css/vuexy/plugins/extensions/ext-component-toastr.css') }}">
    <!-- END: Page CSS-->

    <!-- BEGIN: Custom CSS-->
    <link rel="stylesheet" type="text/css" href="{{ asset('css/vuexy/style.css') }}">
    <!-- END: Custom CSS-->
</head>

resources/views/layouts/navbar.blade.php
<nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
    <div class="container">
        <a class="navbar-brand" href="{{ url('/') }}">
            {{ config('app.name', 'Laravel') }}
        </a>

        <div class="dropstart d-block d-md-none ms-auto me-3">
            <a class="notif" href="javascript:void(0);" data-toggle="dropdown" data-bs-toggle="dropdown"
                data-bs-display="static" id="notif">
                <i data-feather="bell"></i>
                {{-- <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger jmlh-notif"
                    id="jmlh-notif">2</span> --}}
            </a>
            <ul class="dropdown-menu dropdown-menu-start">
                <li class="dropdown-header mx-4">
                    <div class="d-flex justify-content-between">
                        <h4 class="notification-title mb-0 me-5">Notifications</h4>
                        <h4
                            class="badge rounded-pill bg-secondary bg-opacity-25 text-primary text-opacity-75 align-self-center ">
                            5 New
                        </h4>
                    </div>
                </li>
                <li>
                    <hr class="dropdown-divider">
                </li>
                <li class="notifications" id="notifications">
                </li>
                <li>
                    <hr class="dropdown-divider">
                </li>
                <li class="dropdown-menu-footer py-2 d-flex justify-content-center">
                    <a class="btn btn-primary btn-block dropdown-item" href="javascript:void(0)">Read
                        all notifications</a>
                </li>
            </ul>
        </div>

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <!-- Left Side Of Navbar -->
            <ul class="navbar-nav me-auto">
            </ul>

            <!-- Right Side Of Navbar -->
            <ul class="navbar-nav ms-auto">
                <!-- Authentication Links -->
                @guest
                    @if (Route::has('login'))
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                        </li>
                    @endif
                    @if (Route::has('register'))
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                        </li>
                    @endif
                @else
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('customer.home') }}">{{ __('Dashboard') }}</a>
                    </li>
                    {{-- <li class="nav-item">
                            <a class="nav-link" href="{{ route('customer.notifikasi') }}">{{ __('Notifikasi') }}</a>
                        </li> --}}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('customer.cart') }}">{{ __('Cart') }}</a>
                    </li>
                    <li class="nav-item dropdown dropdown-notification mr-25 d-none d-sm-block">
                        {{-- <a class="nav-link" href="javascript:void(0);" data-toggle="dropdown">
                                <i data-feather="bell"></i>
                                <span
                                    class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger">
                                    5
                                </span>
                                <ul class="dropdown-menu dropdown-menu-media dropdown-menu-right">
                                    <li class="dropdown-menu-header">
                                        <div class="dropdown-header d-flex">
                                            <h4 class="notification-title mb-0 mr-auto">Notifications</h4>
                                            <div class="badge badge-pill badge-light-primary">6 New</div>
                                        </div>
                                    </li>
                                    <li class="scrollable-container media-list">
                                        <a class="d-flex" href="javascript:void(0)">
                                            <div class="media d-flex align-items-start">
                                                <div class="media-body">
                                                    <p class="media-heading">
                                                        <span class="font-weight-bolder">Congratulation Sam 🎉</span>winner!
                                                    </p>
                                                    <small class="notification-text"> Won the monthly best seller
                                                        badge.</small>
                                                </div>
                                            </div>
                                        </a>
                                    </li>
                                    <li class="dropdown-menu-footer"><a class="btn btn-primary btn-block"
                                            href="javascript:void(0)">Read all notifications</a></li>
                                </ul>
                            </a> --}}
                        <a class="nav-link notif" href="javascript:void(0);" data-bs-toggle="dropdown"
                            data-bs-auto-close="false" aria-expanded="false" id="notif">
                            <i data-feather="bell"></i>
                            {{-- <span
                                class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger jmlh-notif"
                                id="jmlh-notif"></span> --}}
                            {{-- @isset($jumlah)
                                    <span
                                        class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger">
                                        {{ $jumlah }}
                                    </span>
                                @endisset --}}
                        </a>
                        <ul class="dropdown-menu dropdown-menu-start">
                            {{-- @if (isset($notif))
                                    <li class="dropdown-header mx-4">
                                        <div class="d-flex justify-content-between">
                                            <h4 class="notification-title mb-0 me-5">Notifications</h4>
                                            @isset($jumlah)
                                                <h4
                                                    class="badge rounded-pill bg-secondary bg-opacity-25 text-primary text-opacity-75 align-self-center">
                                                    {{ $jumlah }} New</h4>
                                            @endisset
                                        </div>
                                    </li>
                                    <li>
                                        <hr class="dropdown-divider">
                                    </li>
                                    <li><a class="dropdown-item" href="#">Judul Notifikasi<br><small
                                            class="text-muted">Isi konten notifikasi
                                            yang akan ditampilkan ke notifikasi</small>
                                    </a>
									</li>
                                    <li id="notifications">
                                        <ul class="dropdown-item">

                                        </ul>
                                    </li>
                                    @forelse ($notif as $item)
                                        <li>
                                            <a class="dropdown-item pb-2" href="#">
                                                <span class="fs-5">{{ $item->judul }}</span><br>
                                                <small class="text-muted">{{ $item->isi_pesan }}</small>
                                            </a>
                                        </li>
                                    @empty
                                        <li>
                                            <p class="dropdown-item" href="#">Tidak ada notifikasi<br>
                                            </p>
                                        </li>
                                    @endforelse
                                    <li>
                                        <hr class="dropdown-divider">
                                    </li>
                                    <li class="dropdown-menu-footer py-2 d-flex justify-content-center">
                                        <a class="btn btn-primary btn-block dropdown-item" href="javascript:void(0)">Read
                                            all notifications</a>
                                    </li>
                                @else
                                    <li class="dropdown-header mx-4">
                                        <div class="d-flex justify-content-between">
                                            <h4 class="notification-title mb-0 me-5">Notifications</h4>
                                        </div>
                                    </li>
                                    <li>
                                        <hr class="dropdown-divider">
                                    </li>
                                    <li>
                                        <p class="dropdown-item" href="#">Tidak ada notifikasi<br>
                                        </p>
                                    </li>
                                @endif --}}
                            <li class="dropdown-header mx-4">
                                <div class="d-flex justify-content-between">
                                    <h4 class="notification-title mb-0 me-5">Notifications</h4>
                                    <h4
                                        class="badge rounded-pill bg-secondary bg-opacity-25 text-primary text-opacity-75 align-self-center ">
                                        5 New
                                    </h4>
                                </div>
                            </li>
                            <li>
                                <hr class="dropdown-divider">
                            </li>
                            <li class="notifications" id="notifications">
                            </li>
                            <li>
                                <hr class="dropdown-divider">
                            </li>
                            <li class="dropdown-menu-footer py-2 d-flex justify-content-center">
                                <a class="btn btn-primary btn-block dropdown-item" href="javascript:void(0)">Read
                                    all notifications</a>
                            </li>
                        </ul>
                    </li>
                    <li class="nav-item dropdown">
                        <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button"
                            data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                            {{ Auth::user()->nama }}
                        </a>
                        <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{{ route('logout') }}"
                                onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                                {{ __('Logout') }}
                            </a>
                            <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                @csrf
                            </form>
                        </div>
                    </li>
                @endguest
            </ul>
        </div>
    </div>
</nav>

resources/views/layouts/script-admin.blade.php
<!-- BEGIN: Vendor JS-->
<script src="{{ asset('js/vuexy/vendors.min.js') }}"></script>
<script src="https://unpkg.com/feather-icons"></script>
<!-- BEGIN Vendor JS-->

<!-- BEGIN: Page Vendor JS-->
<script src="{{ asset('js/vuexy/charts/apexcharts.min.js') }}"></script>
{{-- <script src="https://cdn.jsdelivr.net/npm/apexcharts"></script> --}}
{{-- <script src="{{ asset('js/vuexy/extensions/toastr.min.js') }}"></script> --}}
<!-- END: Page Vendor JS-->

<!-- BEGIN: Theme JS-->
<script src="{{ asset('js/vuexy/core/app-menu.js') }}"></script>
<script src="{{ asset('js/vuexy/core/app.js') }}"></script>
<!-- END: Theme JS-->

<!-- BEGIN: SWAL2 JS-->
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11.4.26/dist/sweetalert2.all.min.js"></script>
<!-- END: SWAL2 JS-->

<script>
    $(window).on('load', function() {
        if (feather) {
            feather.replace({
                width: 14,
                height: 14
            });
        }
    })
</script>
{{-- <script>
    navigator.serviceWorker.register('sw.js');

    if (Notification.premission === "granted") {
        navigator.serviceWorker.ready.then((registration) => {
            registration.showNotification('{{ $notif->judul }}', {
                body: '{{ $notif->isi_pesan }}',
                icon: "/logo.png",
            });
        });
    } else if (Notification.permission !== "denied") {
        Notification.requestPermission(function(result) {
            if (result === 'granted') {
                navigator.serviceWorker.ready.then((registration) => {
                    registration.showNotification('{{ $notif->judul }}', {
                        body: '{{ $notif->isi_pesan }}',
                        icon: "/logo.png",
                    });
                });
            }
        });
    }
</script> --}}